### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FilleDev** [onebone/Rino#1]
Hello Onebone!

Can you add so you can set the NPC invinsible so I can use this plugin as floating texts also? Can you also add so you can set the NPC to execute a command if you click it. 

Many thanks!

Best Regards, 
File14

**Comment by FilleDev** [comment]
@onebone

**Comment by onebone** [comment]
After July 3. I'm in exam period.

Commands can be executed if you start message with '/'. Issuer will be always the player though.

**Comment by FilleDev** [comment]
Okay, is there somehow I can remove the leash that appears once I create the NPC and goes all the way above the NPC's username. Some easy code to remove it?

**Comment by onebone** [comment]
@File14 Have you tried https://github.com/MCFT-Server/FloatingText instead of hiding NPC?

**Comment by FilleDev** [comment]
Lol, this is a long time ago. I've coded my own NPC & Floating text plugins now. :p

**Comment by onebone** [comment]
:+1: Will close this issue then
