### ISSUE TITLE
Big Problem

### ISSUE THREAD

**Issue by OverTook** [onebone/Rino#2]
> Exception in thread "main" java.lang.NoClassDefFoundError: cn/nukkit/network/protocol/RemovePlayerPacket
>         at me.onebone.rino.Main.onCommand(Main.java:269)
>         at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
>         at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
>         at cn.nukkit.Server.dispatchCommand(Server.java:628)
>         at cn.nukkit.Player.handleDataPacket(Player.java:2731)
>         at cn.nukkit.network.Network.processPackets(Network.java:193)
>         at cn.nukkit.network.Network.processBatch(Network.java:164)
>         at cn.nukkit.Player.handleDataPacket(Player.java:1794)
>         at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
>         at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
>         at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
>         at cn.nukkit.network.Network.processInterfaces(Network.java:75)
>         at cn.nukkit.Server.tick(Server.java:980)
>         at cn.nukkit.Server.tickProcessor(Server.java:781)
>         at cn.nukkit.Server.start(Server.java:761)
>         at cn.nukkit.Server.<init>(Server.java:455)
>         at cn.nukkit.Nukkit.main(Nukkit.java:65)
> Caused by: java.lang.ClassNotFoundException: cn.nukkit.network.protocol.RemovePlayerPacket
>         at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
>         at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 17 more
> "/rino create <name>" 칠 경우 발생합니다. 무엇이 문제일까요?

**Comment by OverTook** [comment]
@onebone /rino create 이 아니라 /rino create "name" 칠 경우 발생입니다. ㄷ.

항상 감사합니다 ^^;;

**Comment by onebone** [comment]
이미 해결된 문제입니다. GitHub 레포에서 받아서 빌드해주세요.
